/* GPU texture baking: wood, brass and burlap are drawn once by fragment shaders into mipmapped render targets.
   Each bake is split into tiles with a frame between them, so the loader can report real progress.
   One material per fragment shader is kept for all its bakes (only uniforms change), so each shader compiles once:
   engines that compile synchronously (Firefox, Safari) otherwise spend ~0.9 s per bake recompiling the same program. */
import * as THREE from 'three';
import { GLSL_NOISE, breathe } from './util.js';

const VERT = 'varying vec2 vUv; void main() { vUv = uv; gl_Position = vec4(position.xy, 0.0, 1.0); }';

export function createBaker(renderer) {
  const scene = new THREE.Scene();
  const cam = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
  const quad = new THREE.Mesh(new THREE.PlaneGeometry(2, 2));
  quad.frustumCulled = false;
  scene.add(quad);
  const maxAniso = renderer.capabilities.getMaxAnisotropy();
  const materials = new Map();
  function materialFor(fragment, uniforms, width, height, mode) {
    let mat = materials.get(fragment);
    if (!mat) {
      mat = new THREE.ShaderMaterial({
        uniforms: { uRes: { value: new THREE.Vector2() }, uMode: { value: 0 } },
        vertexShader: VERT, fragmentShader: fragment, depthTest: false, depthWrite: false
      });
      materials.set(fragment, mat);
    }
    for (const k in uniforms) { if (mat.uniforms[k]) mat.uniforms[k].value = uniforms[k].value; else mat.uniforms[k] = { value: uniforms[k].value }; }
    mat.uniforms.uRes.value.set(width, height);
    mat.uniforms.uMode.value = mode;
    return mat;
  }

  async function bake({ fragment, uniforms = {}, width, height, srgb = false, mode = 0, tiles = 2 }) {
    const rt = new THREE.WebGLRenderTarget(width, height, {
      depthBuffer: false, type: THREE.UnsignedByteType,
      colorSpace: srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace,
      generateMipmaps: false, minFilter: THREE.LinearMipmapLinearFilter, magFilter: THREE.LinearFilter,
      wrapS: THREE.RepeatWrapping, wrapT: THREE.RepeatWrapping, anisotropy: Math.min(8, maxAniso)
    });
    quad.material = materialFor(fragment, uniforms, width, height, mode);
    const prevTarget = renderer.getRenderTarget();
    const th = Math.ceil(height / tiles);
    for (let i = 0; i < tiles; i++) {
      rt.scissor.set(0, i * th, width, Math.min(th, height - i * th));
      rt.scissorTest = true;
      // mipmaps are generated by three at the end of the render that writes the last tile
      if (i === tiles - 1) rt.texture.generateMipmaps = true;
      renderer.setRenderTarget(rt);
      renderer.render(scene, cam);
      if (i < tiles - 1) await breathe();
    }
    rt.scissorTest = false;
    renderer.setRenderTarget(prevTarget);
    return rt.texture;
  }
  function dispose() { materials.forEach((m) => m.dispose()); materials.clear(); }
  return { bake, dispose };
}

/* ---------- Wood: planks, caulked seams or V-grooves, figure, pores, wear and cup rings ---------- */
export const WOOD_FRAG = /* glsl */`
precision highp float;
varying vec2 vUv;
uniform int uMode; uniform vec2 uRes;
uniform vec2 uSize; uniform float uPlank, uJoint, uVertical, uCaulk, uGroove, uSeed, uFigure;
uniform vec3 uColA, uColB, uColC, uCaulkCol;
uniform vec4 uWear, uRing1, uRing2;
${GLSL_NOISE}
struct WoodS { vec3 col; float h; float r; };
WoodS wood(vec2 q, bool full) {
  vec2 p = uVertical > 0.5 ? vec2(q.y, q.x) : q;
  WoodS o;
  float pl = uPlank > 0.0 ? floor(p.y / uPlank) : 0.0;
  float fy = uPlank > 0.0 ? fract(p.y / uPlank) : 0.5;
  float rA = hash11(pl * 7.13 + uSeed);
  float jl = max(uJoint, 0.001) * (0.75 + 0.5 * rA);
  float jx = (p.x + rA * 3.7) / jl;
  float ji = uJoint > 0.0 ? floor(jx) : 0.0;
  float fx = uJoint > 0.0 ? fract(jx) : 0.5;
  float id = hash12(vec2(pl, ji) + uSeed * 1.37);
  vec2 g = p + vec2(id * 41.0, id * 3.3);
  float warp = fbm3o(vec2(g.x * 1.1, g.y * 5.0)) - 0.5;
  float ringC = g.y * 55.0 * uFigure + warp * 5.0 + fbm3o(vec2(g.x * 0.35, g.y * 2.0)) * 7.0;
  float rings = pow(0.5 + 0.5 * sin(ringC * 6.2831), 3.0);
  float fine = fbm(vec2(g.x * 3.0, g.y * 260.0));
  float pores = vnoise(vec2(g.x * 700.0, g.y * 2600.0));
  float h = fine * 0.25 + rings * 0.14 + (pores - 0.5) * 0.22;
  float rough = mix(0.34, 0.54, fine) + (1.0 - pores) * 0.06;
  vec3 col = vec3(0.0);
  if (full) {
    float streak = smoothstep(0.52, 0.82, fbm3o(vec2(g.x * 0.8, g.y * 90.0) + 13.0));
    float board = mix(0.80, 1.16, id) * (0.9 + 0.2 * vnoise(vec2(g.x * 2.0, g.y * 12.0) + 5.0));
    col = mix(uColA, uColB, clamp(fine * 1.25 - 0.12 + rings * 0.4, 0.0, 1.0));
    col = mix(col, uColC, streak * 0.55 + rings * 0.14);
    col *= board * (0.93 + 0.14 * pores);
    rough += streak * 0.06;
    h -= streak * 0.06;
  }
  if (uPlank > 0.0) {
    float dy = min(fy, 1.0 - fy) * uPlank;
    float dx = uJoint > 0.0 ? min(fx, 1.0 - fx) * jl : 1.0;
    float d = min(dy, dx);
    if (uCaulk > 0.5) {
      float cw = 0.0021;
      float c = 1.0 - smoothstep(cw - 0.0004, cw + 0.0003, d);
      col = mix(col, uCaulkCol * (0.8 + 0.4 * pores), c);
      rough = mix(rough, 0.66, c);
      h = mix(h, -1.1, c);
      h -= (1.0 - smoothstep(cw, cw + 0.0022, d)) * 0.4;
    } else {
      float v = 1.0 - smoothstep(0.0, uGroove, d);
      h -= v * v * 3.0;
      col *= 1.0 - v * v * 0.6;
    }
  }
  o.col = col; o.h = h; o.r = rough;
  return o;
}
void main() {
  vec2 q = vUv * uSize;
  if (uMode == 2) {
    vec2 e = uSize / uRes;
    float hl = wood(q - vec2(e.x, 0.0), false).h, hr = wood(q + vec2(e.x, 0.0), false).h;
    float hd = wood(q - vec2(0.0, e.y), false).h, hu = wood(q + vec2(0.0, e.y), false).h;
    float k = 0.00032;
    vec3 n = normalize(vec3(-(hr - hl) * k / (2.0 * e.x), -(hu - hd) * k / (2.0 * e.y), 1.0));
    gl_FragColor = vec4(n * 0.5 + 0.5, 1.0);
    return;
  }
  WoodS w = wood(q, true);
  vec3 col = w.col; float rough = w.r;
  if (uWear.w > 0.0) {
    float wd = length((q - uWear.xy) / vec2(1.0, 0.55)) / uWear.z;
    float wear = (1.0 - smoothstep(0.15, 1.0, wd + (fbm3o(q * 9.0) - 0.5) * 0.7)) * uWear.w;
    col = mix(col, col * vec3(1.3, 1.2, 1.08) + vec3(0.012, 0.008, 0.004), wear);
    rough = mix(rough, 0.74, wear * 0.85);
  }
  for (int i = 0; i < 2; i++) {
    vec4 R = i == 0 ? uRing1 : uRing2;
    if (R.w <= 0.0) continue;
    vec2 dq = q - R.xy;
    float rr = length(dq), an = atan(dq.y, dq.x);
    float band = exp(-pow((rr - R.z) / 0.0017, 2.0)) * (0.55 + 0.45 * vnoise(vec2(an * 9.0, R.x * 7.0)));
    float fill = (1.0 - smoothstep(R.z - 0.006, R.z, rr)) * 0.18;
    float gap = smoothstep(0.25, 0.55, vnoise(vec2(an * 2.2 + R.y * 13.0, 0.5)));
    float m = clamp(band + fill, 0.0, 1.0) * R.w * gap;
    col *= 1.0 - m * 0.5;
    rough = mix(rough, 0.24, m * 0.75);
  }
  if (uMode == 0) gl_FragColor = vec4(col, 1.0);
  else gl_FragColor = vec4(1.0, clamp(rough, 0.05, 1.0), 0.0, 1.0);
}
`;

/* ---------- Brass: polish, brushing, tarnish in the hollows (tiles) ---------- */
export const BRASS_FRAG = /* glsl */`
precision highp float;
varying vec2 vUv;
uniform int uMode; uniform vec2 uRes;
${GLSL_NOISE}
float field(vec2 p, out float tarnish) {
  tarnish = smoothstep(0.52, 0.78, pfbm(p * 6.0, vec2(6.0))) * 0.8 + smoothstep(0.7, 0.9, pnoise(p * 60.0, vec2(60.0))) * 0.3;
  float brush = pnoise(vec2(p.x * 8.0, p.y * 520.0), vec2(8.0, 520.0));
  float pits = smoothstep(0.82, 0.95, pnoise(p * 180.0, vec2(180.0)));
  return brush * 0.35 - pits * 0.8 + tarnish * 0.1;
}
void main() {
  vec2 p = vUv;
  float t;
  float h = field(p, t);
  if (uMode == 0) {
    vec3 polished = vec3(0.80, 0.56, 0.24);
    vec3 aged = vec3(0.30, 0.20, 0.09);
    vec3 col = mix(polished, aged, clamp(t, 0.0, 1.0));
    col *= 0.9 + 0.1 * pnoise(p * 30.0, vec2(30.0));
    gl_FragColor = vec4(col, 1.0);
  } else if (uMode == 1) {
    float r = 0.2 + t * 0.32 + pnoise(vec2(p.x * 8.0, p.y * 520.0), vec2(8.0, 520.0)) * 0.08;
    gl_FragColor = vec4(1.0, r, 1.0, 1.0);
  } else {
    vec2 e = 1.0 / uRes; float tt;
    float hx = field(p + vec2(e.x, 0.0), tt) - field(p - vec2(e.x, 0.0), tt);
    float hy = field(p + vec2(0.0, e.y), tt) - field(p - vec2(0.0, e.y), tt);
    vec3 n = normalize(vec3(-hx * 1.6, -hy * 1.6, 1.0));
    gl_FragColor = vec4(n * 0.5 + 0.5, 1.0);
  }
}
`;

/* ---------- Burlap: an open plain weave of hairy jute threads (tiles) ---------- */
export const BURLAP_FRAG = /* glsl */`
precision highp float;
varying vec2 vUv;
uniform int uMode; uniform vec2 uRes;
${GLSL_NOISE}
const float N = 22.0;
float bump(float x, float w) { float d = abs(x - 0.5) / w; return d < 1.0 ? sqrt(1.0 - d * d) : 0.0; }
float weave(vec2 p, out float gap, out float fib) {
  vec2 a = p * N;
  vec2 i = floor(a), f = fract(a);
  float wA = 0.34 + 0.08 * hash11(mod(i.x, N) * 3.1);
  float wB = 0.34 + 0.08 * hash11(mod(i.y, N) * 5.7 + 11.0);
  bool warpTop = mod(i.x + i.y, 2.0) < 1.0;
  float warp = bump(f.x, wA) * (warpTop ? 0.62 + 0.38 * sin(3.14159 * f.y) : 0.42 - 0.2 * sin(3.14159 * f.y));
  float weft = bump(f.y, wB) * (!warpTop ? 0.62 + 0.38 * sin(3.14159 * f.x) : 0.42 - 0.2 * sin(3.14159 * f.x));
  fib = pnoise(vec2(p.x * N * 2.0, p.y * 900.0), vec2(N * 2.0, 900.0)) * step(weft, warp) + pnoise(vec2(p.x * 900.0, p.y * N * 2.0), vec2(900.0, N * 2.0)) * step(warp, weft);
  float h = max(warp, weft);
  gap = 1.0 - smoothstep(0.02, 0.18, h);
  return h + (fib - 0.5) * 0.12;
}
void main() {
  vec2 p = vUv; float gap, fib;
  float h = weave(p, gap, fib);
  if (uMode == 0) {
    float tone = pfbm(p * 5.0, vec2(5.0));
    vec3 jute = mix(vec3(0.30, 0.20, 0.10), vec3(0.50, 0.37, 0.20), tone) * (0.8 + 0.35 * fib);
    jute *= 0.55 + 0.45 * smoothstep(0.0, 0.7, h);
    jute = mix(jute, vec3(0.05, 0.035, 0.02), gap * 0.85);
    gl_FragColor = vec4(jute, 1.0);
  } else if (uMode == 1) {
    gl_FragColor = vec4(1.0 - gap * 0.6, 0.86 + gap * 0.1, 0.0, 1.0);
  } else {
    vec2 e = 1.0 / uRes; float g2, f2;
    float hx = weave(p + vec2(e.x, 0.0), g2, f2) - weave(p - vec2(e.x, 0.0), g2, f2);
    float hy = weave(p + vec2(0.0, e.y), g2, f2) - weave(p - vec2(0.0, e.y), g2, f2);
    vec3 n = normalize(vec3(-hx * 2.2, -hy * 2.2, 1.0));
    gl_FragColor = vec4(n * 0.5 + 0.5, 1.0);
  }
}
`;

export async function bakeSet(baker, frag, uniforms, width, height, tiles, onStep) {
  const map = await baker.bake({ fragment: frag, uniforms, width, height, srgb: true, mode: 0, tiles });
  onStep && onStep();
  const rough = await baker.bake({ fragment: frag, uniforms, width, height, mode: 1, tiles });
  onStep && onStep();
  const normal = await baker.bake({ fragment: frag, uniforms, width, height, mode: 2, tiles });
  onStep && onStep();
  return { map, rough, normal };
}
