import { KHUNG } from './khung.js';

const so = (k) => String(k).padStart(4, '0');

export const thanChu = (t) => t.replace(/ \| /g, ' ');

export const CHU = {
  trang: {
    ten: 'Blind Alley Pictures · Animation studio, Glasgow',
    moTa: 'Seven animators and a camera operator in a dead-end lane in Glasgow, making ads and music videos from pencil and cut paper.',
  },
  studio: {
    tieuDe: 'Everyone here carries a blade.',
    than: [
      'Seven animators and a camera operator, | in one room in Glasgow.',
      'You’ll know every one of them | by name before we start.',
      'Ads and music videos, | in pencil and cut paper.',
    ],
    goiY: 'Scroll to roll film',
    nhan: 'Animation studio · Glasgow',
  },
  pho: {
    tieuDe: 'Rain is murder to draw.',
    kieuThan: 'doan',
    than: ['Every drop out here is drawn by hand, and so is the neon in the puddle. A thirty-second ad takes us about eight weeks. You’ll see pencil versions every Friday, while anything can still change.'],
    nhan: null,
    kinh: {
      duoi: 'Murder’s a big word for one frame.',
      son: 'Lipstick. Same red as the ashtray.',
      tui: 'Coat pocket hangs open. Empty now.',
      tay: 'Grey on her glove tips. Pencil, not ash.',
      phim: 'Dropped it, or left it for me?',
      den: 'Quarter past two. Still raining.',
      vet: 'Her prints head back up the lane.',
    },
  },
  lat: {
    tieuDe: 'Everything here goes under glass.',
    kieuThan: 'doan',
    than: ['Your film is paper first. Every frame is drawn, cut and shot once under this camera, and you can come and watch it happen. The computer comes in last, to put the layers together.'],
    nhan: null,
    kinh: {
      duoi: 'So does the evidence.',
      chinh: 'No rain in this one.',
      so: `Edge number ${so(KHUNG)}. That’s the one.`,
      vet: 'Same clean cut. Same steady hand.',
      mep: 'Grey smudge on the edge. Pencil again.',
      ngo: 'It’s the lane. One door lit.',
      mua: 'Who forgets the rain in Glasgow?',
    },
  },
  ngo: {
    tieuDe: 'Nobody finds us by accident.',
    kieuThan: 'doan',
    than: ['We’re hard to find on purpose. Come down the lane, knock on the bookbinder’s door, and the kettle goes on. You’ll sit with the person drawing your film, not an account manager.'],
    nhan: null,
    kinh: {
      chinh: 'Her prints go in. None come out.',
      duoi: 'So she knew the way.',
      ham: 'Three a.m. Cellar light still on.',
      tieng: 'Pencil scratching through the grate.',
      vong: 'Back where I started. Dead ends do that.',
      hoi: 'Who stays up all night for one frame?',
      meo: 'Only witness. Won’t talk.',
      but: 'Pencil stub. Chewed. Same grey as her gloves.',
    },
  },
  ham: {
    tieuDe: 'We stay late for one frame.',
    kieuThan: 'doan',
    than: ['Every drawing we’ve ever made is kept down here. If one frame of your film is wrong, somebody stays late and redraws it by hand. You’ll never be asked to live with it.'],
    nhan: null,
    kinh: {
      chinh: 'Why one frame? The rest had rain.',
      duoi: 'So did I. Same frame, other reasons.',
      tay: 'Grey glove tips. Still drawing rain.',
      but: 'Lipstick on the pencil end. Same red.',
      toi: 'One empty peg. No prize for guessing.',
      kinh: 'Name on the door. Backwards from in here.',
    },
  },
  ban: {
    tieuDe: 'Case closed. Yours is next.',
    kieuThan: 'doan',
    than: ['That’s how we work: slowly, by hand, with the kettle on. Five old files on the desk, a new one waiting. Pull up a chair and tell us about yours.'],
    nhan: null,
    kinh: {
      chinh: 'Frame 0418: back in. Rain restored.',
      duoi: 'Mine took all night. Yours gets weeks.',
      giu: 'Kept the dry one. Call it a souvenir.',
      co: 'She’s back at her desk. No charges.',
    },
    nhanO: { khach: 'Client', dai: 'Running time', cach: 'Method', vu: 'The job', ketQua: 'Outcome' },
    dau: 'CLOSED',
    mo: 'Open file',
    moRa: 'Opened',
    dong: 'close',
    hoSo: [
      { so: '027', loai: 'Ad', nam: 2016, khach: 'Haldane Umbrellas, Glasgow', dai: '30 sec', cach: 'Pencil on paper', vu: 'An umbrella maker, tired of hosing down actors. We drew the downpour instead.', ketQua: 'Their black umbrellas sold out by December.', dong: true, anh: './anh/ho-so-1.webp' },
      { so: '053', loai: 'Music video', nam: 2019, khach: 'The Drowned Clocks, a four-piece from Dundee', dai: '3 min 52 sec', cach: 'Cut-paper silhouettes', vu: 'The band won’t face a camera. We cut all four out of paper.', ketQua: 'Frame 212 ended up on the record sleeve.', dong: true, anh: './anh/ho-so-2.webp' },
      { so: '071', loai: 'Title sequence', nam: 2022, khach: 'Nine Fathoms, a feature thriller', dai: '1 min 50 sec', cach: 'Cut-paper letters, pencil sea', vu: 'The director wanted dread before anyone spoke. We cut the credits and sank them.', ketQua: 'Booked again for the sequel.', dong: true, anh: './anh/ho-so-3.webp' },
      { so: '092', loai: 'Ad', nam: 2024, khach: 'Morrin’s Bakery, Paisley', dai: '60 sec', cach: 'Pencil, drawn from life', vu: 'A bakery wanted its night shift on screen. We did the stakeout with sketchbooks.', ketQua: 'Every baker took home a drawing of themselves.', dong: true, anh: './anh/ho-so-4.webp' },
      { so: '106', loai: 'Short film', nam: 2026, ten: 'The Missing Frame', khach: 'Blind Alley Pictures', dai: '5 min', cach: 'Pencil and cut paper', vu: 'Our short for the year. A detective goes looking for one missing frame.', ketQua: 'Showing now. You’re in the last scene.', dong: false, anh: './anh/ho-so-5.webp' },
    ],
    form: {
      tieuDe: 'Bring us a case.',
      mo: 'Case 107 · Intake · Blind Alley Pictures', moNgan: 'Case 107 · Intake',
      nutMo: 'Bring us a case',
      ten: { nhan: 'Who’s asking?', goiY: 'Your name' },
      email: { nhan: 'How do we reach you?', goiY: 'Email address' },
      loai: { nhan: 'What’s the job?', chon: ['An ad', 'A music video', 'Opening titles', 'Something else'] },
      nganSach: { nhan: 'What’s it worth to you?', goiY: 'A rough figure will do' },
      han: { nhan: 'How long have we got?', goiY: 'The date it has to go out' },
      moTa: { nhan: 'Start at the beginning.', goiY: 'What it’s for, how many seconds, what you have so far' },
      tuyChon: 'optional',
      nut: 'Leave it with us',
      demo: 'Demo form: nothing you type leaves this page.',
      camOnTieuDe: 'Off the record.',
      moiNua: 'Open another file',
      dauGui: 'Filed',
      camOn: 'This form is a demo, so nothing you typed left this page. No need to wait by the phone.',
      loiChung: 'A file with blanks won’t hold up. Fill in the marked lines.',
      loiTen: 'Every file needs a name.',
      loiEmail: 'An email address goes here.',
      loiEmailSai: 'That address won’t reach anyone. Check it?',
      loiLoai: 'Pick the closest one.',
      loiMoTa: 'Give us something to go on.',
    },
    vuot: 'Swipe the files',
    chan: 'Designed & built by Shocking Mike',
  },
  dai: {
    nhan: 'Film reel',
    canh: [{ ten: 'INT. OFFICE · NIGHT', ngan: 'OFFICE', doc: 'Scene 1: interior, office, night' },
      { ten: 'EXT. STREET · NIGHT', ngan: 'STREET', doc: 'Scene 2: exterior, street, night' },
      { ten: 'INSERT · THE FRAME', ngan: 'INSERT', doc: 'Scene 3: insert, close on one frame' },
      { ten: 'EXT. BLIND ALLEY · NIGHT', ngan: 'ALLEY', doc: 'Scene 4: exterior, blind alley, night' },
      { ten: 'INT. CELLAR · NIGHT', ngan: 'CELLAR', doc: 'Scene 5: interior, cellar, night' },
      { ten: 'INT. OFFICE · DAWN', ngan: 'DAWN', doc: 'Scene 6: interior, office, dawn' }],
  },
  tai: { nhan: 'Cutting the titles', xong: 'Titles cut' },
  am: { nhom: 'Sound', co: 'Enter with sound', khong: 'Enter in silence', nut: 'Sound', bat: 'On', tat: 'Off' },
  loi: {
    webgl: 'This film is drawn live with WebGL, and this browser has it switched off. Turn on hardware acceleration, or open the page in another browser.',
    mang: 'Part of the film didn’t arrive. The connection dropped while the reel was loading.',
    loi: 'The reel snagged while loading.',
    cham: 'Still cutting the titles. This connection is slow; it will start on its own.',
    nut: 'Try again',
  },
  kinh: {
    duoi: 'Eight blades here. Check every one.',
    chinh: `Frame ${so(KHUNG)} is missing. Somebody cut it out.`,
    daiSo: [-2, -1, 0, 1, 2, 3].map((d) => ({ so: so(KHUNG + d), mat: d === 0 })),
    haiBen: `${so(KHUNG - 1)} and ${so(KHUNG + 1)} untouched. Just the one.`,
    vetCat: 'Clean cut, both edges. A steady hand.',
    son: 'Someone smoked here before me. Red lipstick.',
    bau: 'Wet prints on the window frame. Raining since nine.',
    gio: 'Reel whole at midnight. Cut by two.',
    tui: 'A single frame fits in a coat pocket.',
    cua: 'One way in. The lane’s a dead end.',
    hoi: 'Why take one frame and leave the rest?',
  },
};
